name: Create password
on: [workflow_dispatch]

jobs:
  create_pass:
    runs-on: ubuntu-latest
    steps:
      - name: Create a password
        uses: planetscale/create-branch-password-action@v1
        id: create_branch_password
        with:
          org_name: bmorrison-ps
          database_name: recipes_db
          branch_name: main
          name: 'alsdkjfaldksjfalskdjf'
        env:
          PLANETSCALE_SERVICE_TOKEN_ID: ${{ secrets.PLANETSCALE_SERVICE_TOKEN_ID }}
          PLANETSCALE_SERVICE_TOKEN: ${{ secrets.PLANETSCALE_SERVICE_TOKEN }}
      - name: Get the new credentials
        run: |
          echo "Hostname: ${{ steps.create_branch_password.outputs.hostname }}"
          echo "Username: ${{ steps.create_branch_password.outputs.username }}"
          echo "Password: ${{ steps.create_branch_password.outputs.password }}"
