on:
  [workflow_dispatch]

name: Docker a thing

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Hello GH Actions!
    steps:
      - name: doathing
        run: |
          mkdir tmp
          docker run planetscale/pscale:latest db ls > help.txt
          ls
          echo "==================="
          cat help.txt
        env:
          PLANETSCALE_SERVICE_TOKEN_ID: ${{ secrets.PLANETSCALE_SERVICE_TOKEN_ID }}
          PLANETSCALE_SERVICE_TOKEN: ${{ secrets.PLANETSCALE_SERVICE_TOKEN }}
