on:
  [workflow_dispatch]

name: Make a branch

jobs:
  make_a_branch:
    runs-on: ubuntu-latest
    name: Create a PlanetScale branch
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Hello world action tests
        uses: planetscale/create-branch-action@64791baaa68ff6e8e913ecc3ea8fbc8fc9c721fa
        id: hello
        with:
          org_name: bmorrison-ps
          database_name: calendar_db
          branch_name: dev
          from: main
          wait: true
          check_exists: true
        env:
          PLANETSCALE_SERVICE_TOKEN_ID: ${{ secrets.PLANETSCALE_SERVICE_TOKEN_ID }}
          PLANETSCALE_SERVICE_TOKEN: ${{ secrets.PLANETSCALE_SERVICE_TOKEN }}
