on:
  push

name: Make a branch

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Hello GH Actions!
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Hello world action tests
        uses: bmorrisondev/ps-actions/create-branch@v0.0.12
        id: hello
        with:
          org_name: bmorrison-ps
          database_name: recipes_db
          branch_name: withscripts
          from: main
          wait: true
        env:
          PLANETSCALE_TOKEN_NAME: ${{ secrets.PLANETSCALE_TOKEN_NAME }}
          PLANETSCALE_TOKEN: ${{ secrets.PLANETSCALE_TOKEN }}
