on:
  [workflow_dispatch]

name: Docker a thing

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Hello GH Actions!
    steps:
      - name: doathing
        run: |
          docker run planetscale/pscale:latest help
