on: [workflow_dispatch]

name: Make a branch

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Hello GH Actions!
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Hello world action tests
        uses: bmorrisondev/create-branch-action@v0.0.2
        id: hello
        with:
          org_name: bmorrison-ps
          database_name: recipes_db
          branch_name: firstrun
          source_branch: rawr
        env:
          PLANETSCALE_TOKEN_NAME: ${{ secrets.PLANETSCALE_TOKEN_NAME }}
          PLANETSCALE_TOKEN: ${{ secrets.PLANETSCALE_TOKEN }}
      # - name: Get the output time
      #   run: echo "The time was ${{ steps.hello.outputs.time }}"
