on:
  [workflow_dispatch]

name: Docker a thing

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Hello GH Actions!
    steps:
      - name: doathing
        run: |
          mkdir tmp
          docker run -v tmp:/tmp  planetscale/pscale:latest help > /tmp/help.txt
          ls
          ls tmp
          cat tmp/help.txt
