on:
  [workflow_dispatch]

name: Docker a thing

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Hello GH Actions!
    steps:
      - name: doathing
        run: |
          mkdir tmp
          docker run planetscale/pscale:latest help > help.txt
          ls
          echo "==================="
          cat help.txt
