on:
  push

name: Make a branch

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Hello GH Actions!
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Hello world action tests
        uses: bmorrisondev/ps-actions/create-password@v0.0.11
        id: hello
        with:
          org_name: bmorrison-ps
          database_name: recipes_db
          branch_name: main
          name: pass123asd
        env:
          PLANETSCALE_TOKEN_NAME: ${{ secrets.PLANETSCALE_TOKEN_NAME }}
          PLANETSCALE_TOKEN: ${{ secrets.PLANETSCALE_TOKEN }}
      - name: Echo the creds
        run: echo "Username - ${{ steps.hello.outputs.username }}\nHostname - ${{ steps.hello.outputs.hostname }}"
